name: appium_driver_example
description: An example of appium_dart
version: 0.0.1
author: 'Kazuaki Matsuo <fly.49.89.over@gmail.com>'
homepage: https://github.com/KazuCocoa/appium_dart
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  appium_driver: any
  test: '^1.0.0'
