name: appium_dart
description: An appium client in Dart
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  webdriver: '>=2.0.0'

dev_dependencies:
  test: '^1.0.0'
