name: appium_driver
description: >
  An Appium binding for Dart.
  Support WebDriver W3C spec inheriting webdriver.dart.
version: 0.7.1
homepage: https://github.com/KazuCocoa/appium_dart
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  webdriver: '^3.0.0'

dev_dependencies:
  test: '>=1.17.0'
  pana: ">=0.17.0 <0.23.0"
