name: appium_driver
description: >
  An Appium binding for Dart.
  Support WebDriver W3C spec inheriting webdriver.dart.
version: 0.2.2
homepage: https://github.com/KazuCocoa/appium_dart
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  webdriver: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: '^1.0.0'
  pana: '^0.13.0'
